---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-source-git
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: infrastructure
  url: https://github.com/subirchatterjee/bb-app-source.git
